version: '3.8'

services:
  webapp-db:
    image: mariadb:latest
    container_name: webapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: webapp-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: AStrongAndSecurePassword123!!!
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
