version: '3.8'
networks:
    webapp-network:
        driver: bridge
services:
  webapp-db:
    image: mariadb:latest
    container_name: webapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
        - webapp-network
  webapp:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: webapp
    restart: always
    ports:
      # Expose port 80 to host on localhost
      - "80:80"
      - "443:443"
    networks:
        - webapp-network
    volumes:
      - ./webapp_logs:/app/logs

volumes:
  mariadb_data:
